config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'users#home', as: 'user_home'

  resources :activities, only: [:index, :show]

  devise_for :users

  namespace :users, path: 'users/:user_id', as: 'user' do
    resources :activities
  end

  get 'faq' => 'pages#faq'

  root 'pages#home'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  self.inheritance_column = nil
  TYPES = %w(Timed Counted)

  validates :name, presence: true
  validates :type, inclusion: { in: TYPES }
  validates :name, uniqueness: { scope: :type, message: 'has already been taken for this type of activity' }

  has_and_belongs_to_many :users, join_table: :user_activities

  def name=(name)
    write_attribute(:name, name.try(:strip))
  end

  def description=(description)
    write_attribute(:description, description.try(:strip))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :activities, join_table: :user_activities

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.joins(:users).where('user_activities.user_id IS NOT NULL').all.sort_by{|a| a.users.size }.reverse
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_params
    params.require(:activity).permit(:name, :description, :type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to user_home_path if user_signed_in?
  end

  def faq
  end
end

app/controllers/users/activities_controller.rb
class Users::ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = @user.activities.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        @user.activities << @activity
        format.html { redirect_to [@user, @activity], notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: [@user, @activity] }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user     = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_params
    params.require(:activity).permit(:name, :description, :type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def home
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.haml
%h1 Popular Activities

%table
  %tr
    %th.text-center Type
    %th Name
    %th Description
    %th.text-right Users

  - @activities.each do |activity|
    %tr
      %td.text-center= icon activity.type.dasherize.downcase + ' fa-fw'
      %td
        %strong= activity.name
      %td= activity.description
      %td.text-right= activity.users.size

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity.name
%p
  %b Description:
  = @activity.description
%p
  %b Type:
  = @activity.type

%p
  %b Users:
  = @activity.users.size

app/views/layouts/_header.html.haml
.contain-to-grid.fixed
  %nav.top-bar{ role: 'navigation', data: { topbar: true }}
    %ul.title-area
      %li.name
        %h1= link_to 'Mastery', root_path
      %li.toggle-topbar.menu-icon
        = link_to '#' do
          %span
    %section.top-bar-section
      - if user_signed_in?
        %ul.right
          %li.has-dropdown
            = link_to '#' do
              = icon 'cubes fa-fw'
              Activities
            %ul.dropdown
              - Activity::TYPES.sort.each do |type|
                - current_user.activities.where(type: type).order(:name).each do |activity|
                  %li
                    = link_to [current_user, activity] do
                      = icon "#{activity.type.dasherize.downcase} fa-fw"
                      = activity.name
                %li.divider
              %li
                = link_to new_user_activity_path(current_user.id) do
                  = icon 'plus fa-fw'
                  New Activity
          %li.divider
          %li
            = link_to destroy_user_session_path, method: :delete do
              = icon('power-off fa-fw')
              Sign Out
      - else
        %ul.right
          %li
            = link_to new_user_registration_path do
              = icon 'pencil fa-fw'
              Sign Up
          %li.divider
          %li
            = link_to new_user_session_path do
              = icon 'arrow-circle-right fa-fw'
              Sign In

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Mastery
      = ' | ' + content_for(:title) if content_for?(:title)
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    %main= yield
    %footer.page-footer

app/views/pages/faq.html.haml
%h1 Pages#faq
%p Find me in app/views/pages/faq.html.haml

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.haml

app/views/users/activities/_form.html.haml
.row
  .medium-8.columns.medium-centered
    = form_for [@user, @activity] do |f|
      - if @activity.errors.any?
        #error_explanation
          %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
          %ul
            - @activity.errors.full_messages.each do |msg|
              %li= msg

      .row
        .medium-4.columns
          = f.label :name, class: 'inline'
        .medium-8.columns
          = f.text_field :name
      .row
        .medium-4.columns
          = f.label :description, class: 'inline'
        .medium-8.columns
          = f.text_area :description
      .row
        .medium-4.columns
          = f.label :type, class: 'inline'
        .medium-8.columns
          = f.select :type, Activity::TYPES, prompt: 'Activity Type'
      .row
        .medium-8.columns.right
          = f.button class: 'expand' do
            = icon 'save fa-fw'
            Save

app/views/users/activities/edit.html.haml
%h1 Editing #{link_to @activity.name, @activity}

= render 'form'

app/views/users/activities/index.html.haml
%h1 My Activities

%table
  %tr
    %th.text-center Type
    %th Name
    %th Description

  - @activities.each do |activity|
    %tr
      %td.text-center= icon activity.type.dasherize.downcase + ' fa-fw'
      %td
        %strong= activity.name
      %td= activity.description

= link_to 'New Activity', new_user_activity_path(@user)

app/views/users/activities/new.html.haml
%h1 New activity

= render 'form'

app/views/users/activities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity.name
%p
  %b Description:
  = @activity.description
%p
  %b Type:
  = @activity.type

%p
  %b Users:
  = @activity.users.size

app/views/users/home.html.haml
%h1 Users#home
%p Find me in app/views/users/home.html.haml